aws_vpc_id              = "vpc-0d6dfb97ce2892897"
aws_region              = "ca-central-1"
aws_account             = "486102663181"
aws_api_vpc_endpoint    = "vpce-012f965ab5aa1175a"
provisioner_environment = "onequicklab"
templates_bucket_name   = "onequicklab-lambda-provisioner"
provisioner_keypair     = "onequicklab-lambda-provisioner"
provisioner_api_name    = "OneQuickLabProvisioner"
provisioner_api_stage   = "onequicklab"

